### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by charis-the-programmer** [michaeldera/edliz#2]
Well done with this project! I am interested in contributing by converting this into a hybrid mobile app. However, I see the EDLIS is © Copyright June 2015, Ministry of Health & Child Care. Did you get the necessary permission to reproduce this in digital form?

Kind Regards

**Comment by michaeldera** [comment]
## Copyright Issues
Hie @charis-the-programmer. We have ongoing conversation with the Ministry about this and there are no issue with converting this to digital form as long as the purposes are non-commercial. 

There will be no conflict with the Ministry as long as that remains the same. In any case, should there be any issues they would be directly at myself.


## Roadmap
In relation to setting up a Hybrid application, may I suggest that if you wll go that route you set up a continous integration pipeline as there will be a lot of changes coming to it in the next few weeks. I can give you access to tools to set that up if you are keen 

The approcah that we had taken is to make it a PWA and will be ironing out the issues that you may have noticed. The master branch is on a continuous integration pipeline which is live on [right here](https://edliz.azurewebsite.net). We will probably introduce a new link on a .org.zw domain and use the current one as a preview directory

## Contributing 
Contributiong are encouraged! Please feel free. Part of the reason we open source it was to all people like yourself to help out
