### ISSUE TITLE
[BUG] Remove <a> tag in chapters

### ISSUE THREAD

**Issue by mcheartno** [michaeldera/edliz#27]
**Describe the bug**
In your chapters, all heading encapsulate an `a` tag. I think this is unnecessary as thats not how and why an <a> tag is supposed to be used there.

_The <a> tag defines a hyperlink, which is used to link from one page to another. The most important attribute of the <a> element is the href attribute, which indicates the link's destination._

In this project the multiple headings in the chapters are not links, and thus we have errors in our code due to the <a> tag not having an href. If we are to clean our code to have as few errors as possible, let us remove tag.

**Comment by michaeldera** [comment]
The tags are meant to be there, it is incomplete content. There are parts of the content that are meant to other sections of the guidelines. So seeing as we addressed in-App routing now we can modify the content to go to the relevant areas

**Comment by michaeldera** [comment]
You can remove the areas where the tags existing if it slows aspects of your work done and each link will be added on a case by case basis as content as review in each area

**Comment by Noeza** [comment]
Can we jump on a 5 min call so you explain to me. If i its clear i can do the work which is no problem

**Comment by Noeza** [comment]
I added linting rules to the project, which i will show you shortly. One of the rules is to ensure we dont have `a `tags with no href, it defeats the purpose. I can disable that rule for now if those tags are of use,
