### ISSUE TITLE
[FEATURE] Persisting preferences

### ISSUE THREAD

**Issue by bzmp125** [michaeldera/edliz#66]
**Is your feature request related to a problem? Please describe.**
Preferences are reset when the site is reloaded.

**Describe the solution you'd like**
The user's preferences can be stored in localStorage in the browser and applied when the site is loaded.

**Describe alternatives you've considered**
IndexedDB and WebSQL are alternative storage but LocalStorage has a cleaner API to store and  access the preferences. WebSQL uses a query like language which seems like an over kill for storing an object.

Cookies would also be an alternative but perhaps later for when the site is served from a backend (and not client side) so that security flags can be set from the server side.

**Additional context**
n/a.

**Comment by michaeldera** [comment]
Thank you @bzmp125 Merged #67. Please include your name in the Readme file in another PR then we close this Issue

**Comment by bzmp125** [comment]
My bad, missed that. 

Done in #70.

**Comment by michaeldera** [comment]
Thank you!
